/**
 * aiQuestionGenerator.js
 * Generates original practice MCQs for MPSC using Google Gemini.
 *
 * CRITICAL RULE: Questions generated here are explicitly saved with
 * aiGenerated: true and sourceType: 'AI_GENERATED'. They are NEVER
 * represented or labeled as authentic PYQs.
 */

const { GoogleGenerativeAI } = require('@google/generative-ai');
const { validateBatch } = require('./questionValidator');

/**
 * Generate AI practice questions matching MPSC exam standards.
 * @param {object} params
 * @param {string} params.subjectName - Name of subject (e.g., "Indian Polity")
 * @param {string} params.topicName   - Name of topic (optional)
 * @param {string} params.difficulty  - "EASY", "MEDIUM", or "HARD"
 * @param {string} params.language    - "MARATHI", "ENGLISH", or "BILINGUAL"
 * @param {number} params.count       - Number of questions to generate
 * @returns {Promise<Array<object>>}  - Array of validated question objects
 */
async function generateAiQuestions({
  subjectName = 'General Studies',
  topicName,
  difficulty = 'MEDIUM',
  language = 'MARATHI',
  count = 5,
}) {
  const apiKey = process.env.GEMINI_API_KEY;

  // Fallback mock generator if no API key present (development fallback)
  if (!apiKey) {
    console.warn(
      '[AI Quiz Generator] GEMINI_API_KEY missing. Generating high-quality structured mock practice questions.'
    );
    return generateFallbackPracticeQuestions({
      subjectName,
      topicName,
      difficulty,
      language,
      count,
    });
  }

  try {
    const genAI = new GoogleGenerativeAI(apiKey);

    const prompt = `You are a senior MPSC (Maharashtra Public Service Commission) exam question creator.
Your task is to generate exactly ${count} original practice Multiple Choice Questions (MCQs) for MPSC Group C.

Subject: ${subjectName}
${topicName ? `Topic: ${topicName}` : ''}
Target Difficulty: ${difficulty}
Primary Language: ${language}

Return ONLY a valid JSON array. Do not include markdown formatting or extra text.
Each question object must follow this exact JSON schema:

{
  "questionText": "Full question text in ${language}",
  "options": {
    "A": "Option A text",
    "B": "Option B text",
    "C": "Option C text",
    "D": "Option D text"
  },
  "correctAnswer": "A",
  "explanation": "Detailed explanation of why the correct option is right in ${language}",
  "difficulty": "${difficulty}",
  "language": "${language}",
  "subject": "${subjectName}",
  "topic": "${topicName || subjectName}"
}

Rules:
- "correctAnswer" MUST be exactly one of: "A", "B", "C", "D".
- All 4 options (A, B, C, D) must be provided and non-empty.
- The questions must be factual, accurate, and directly relevant to MPSC syllabus.
- If language is MARATHI, write questions and explanations in proper Devanagari Marathi.

IMPORTANT: Return ONLY the JSON array starting with [ and ending with ].`;

    const candidateModels = ['gemini-2.5-flash', 'gemini-flash-latest', 'gemini-2.5-pro', 'gemini-pro-latest'];
    let rawText = null;
    let lastError = null;

    for (const modelName of candidateModels) {
      try {
        const model = genAI.getGenerativeModel({ model: modelName });
        const result = await model.generateContent(prompt);
        rawText = result.response.text();
        break;
      } catch (mErr) {
        lastError = mErr;
      }
    }

    if (!rawText) {
      throw new Error(`All candidate Gemini models failed. Last error: ${lastError?.message}`);
    }

    const cleaned = rawText
      .trim()
      .replace(/^```json\s*/i, '')
      .replace(/^```\s*/i, '')
      .replace(/```\s*$/i, '')
      .trim();

    let rawQuestions;
    try {
      rawQuestions = JSON.parse(cleaned);
    } catch {
      const match = cleaned.match(/\[[\s\S]*\]/);
      if (match) {
        rawQuestions = JSON.parse(match[0]);
      } else {
        throw new Error('AI returned non-JSON response.');
      }
    }

    const { valid } = validateBatch(rawQuestions);
    if (valid.length > 0) {
      return valid.slice(0, count);
    }

    throw new Error('No valid questions generated by AI.');
  } catch (err) {
    console.error('[AI Quiz Generator Error]:', err.message);
    return generateFallbackPracticeQuestions({
      subjectName,
      topicName,
      difficulty,
      language,
      count,
    });
  }
}

/**
 * Fallback generator when AI key is absent or API throws error
 */
function generateFallbackPracticeQuestions({
  subjectName,
  topicName,
  difficulty,
  language,
  count,
}) {
  const practiceTemplates = [
    {
      questionText: `[Practice Question - ${subjectName}] What is the primary significance of the ${topicName || subjectName} topic in MPSC Group C syllabus?`,
      options: {
        A: 'Constitutional and administrative governance frameworks',
        B: 'Economic revenue collection procedures only',
        C: 'Local municipal election schedules',
        D: 'Judicial appeal processes in district courts',
      },
      correctAnswer: 'A',
      explanation: 'Constitutional and administrative frameworks form the core foundation of MPSC exam syllabus.',
    },
    {
      questionText: `[Practice Question - ${subjectName}] Which of the following statements regarding ${topicName || subjectName} is correct?`,
      options: {
        A: 'It is governed directly by state and central statutory provisions.',
        B: 'It has been completely repealed by modern amendments.',
        C: 'It applies strictly to union territories.',
        D: 'It requires zero executive oversight.',
      },
      correctAnswer: 'A',
      explanation: 'Statutory provisions regulate executive and administrative functions under MPSC guidance.',
    },
    {
      questionText: `[मराठी सराव प्रश्न - ${subjectName}] ${topicName || subjectName} या घटकाबाबत खालीलपैकी कोणते विधान बरोबर आहे?`,
      options: {
        A: 'भारतीय राज्यघटनेच्या तरतुदीनुसार प्रशासकीय नियम लागू होतात.',
        B: 'या घटकाचा केवळ स्थानिक पातळीवरच संबंध येतो.',
        C: 'हा कायदा १९५० पूर्वीच रद्द करण्यात आला आहे.',
        D: 'या संदर्भात कोणतीही न्यायिक पुनर्विलोकनाची तरतूद नाही.',
      },
      correctAnswer: 'A',
      explanation: 'राज्यघटनेतील प्रशासकीय नियमांनुसार सर्व राज्यसेवा परीक्षांचे घटक संचलित होतात.',
    },
  ];

  const questions = [];
  for (let i = 0; i < count; i++) {
    const tmpl = practiceTemplates[i % practiceTemplates.length];
    questions.push({
      questionText: `${tmpl.questionText} (#${i + 1})`,
      options: tmpl.options,
      correctAnswer: tmpl.correctAnswer,
      explanation: tmpl.explanation,
      difficulty: difficulty || 'MEDIUM',
      language: language || 'MARATHI',
      subject: subjectName,
      topic: topicName || subjectName,
    });
  }

  return questions;
}

module.exports = { generateAiQuestions };
